### ISSUE TITLE
QuickType suggestion bar obscures long notes

### ISSUE THREAD

**Issue by dkono** [toopriddy/mytime#281]
For very long return visit notes (running on an iPhone 5S, OS 8.3), text eventually becomes obscured by the keyboard while typing.  A current workaround is to hide the QuickType suggestion bar; however, it would be nice if the entry field could adjust for this automatically.

**Comment by toopriddy** [comment]
Thank you for the issue report. Could you include the device model number (like iPhone 6 plus) and the version of iOS you are using?

I am currently visiting bethel and will try to look at this soon

Thanks

**Comment by dkono** [comment]
Sorry I didn’t separate this information out clearly in the original.

Device: iPhone 5S
OS: iOS 8.3

Enjoy your Bethel visit!

**Comment by toopriddy** [comment]
This should have been fixed in the 3.7.0 release
