### ISSUE TITLE
iCloud sync support

### ISSUE THREAD

**Issue by petrsel** [toopriddy/mytime#283]
Thank you for making such useful app! It would help a lot to add support for iCloud data syncing so you can view/edit service entries on multiple devices and all will be in sync. Thank you! Petr

**Comment by toopriddy** [comment]
Hello petrsel, Currently you can sync two or more devices using the email
backup feature.  check the frequently asked questions page for
instructions, just search the page for "sync" http://priddysoftware.com/faq

iCloud CoreData syncing is broken in some amazing ways that will cause data
loss and corruption.  Sometimes syncing stops alltogeather and the only way
to get it back working is to delete all of your data.  These are problems
that I am avoiding by not using iCloud CoreData syncing right now.

Thank you!

**Comment by petrsel** [comment]
Thank you for the explanation. And what about 3rd party sync options such as Dropbox folder? This seems to work fine. Thanks! Petr

**Comment by toopriddy** [comment]
Sadly simple file services like Dropbox are not sufficient for database syncing which requires a manifest of individual database entries as well as a merge engine to deal with conflicts

**Comment by toopriddy** [comment]
MyTime has added backup using iCloud file storage.  This is not sync but something.

I am closing this issue report, I use issues as bug reports, not feature requests
