### ISSUE TITLE
language don't change

### ISSUE THREAD

**Issue by jkarous** [toopriddy/mytime#284]

**Comment by toopriddy** [comment]
Hello, MyTime has the same requirements as the JW library that was announced at the service meeting this week. The language the iPhone is in is the same language that MyTime will be in. There is a feature request on the MyTime website to be able to choose different language publications. 

What language is your iPhone set to?

**Comment by jkarous** [comment]
iphone 6s plus greek language. My Time don't change to greek.

2015-10-03 17:57 GMT+03:00 toopriddy <notifications@github.com>:

> Hello, MyTime has the same requirements as the JW library that was
> announced at the service meeting this week. The language the iPhone is in
> is the same language that MyTime will be in. There is a feature request on
> the MyTime website to be able to choose different language publications.
>
> What language is your iPhone set to?
>
> Sent from my iPhone
>

**Comment by toopriddy** [comment]
I was able to set the language to Greek and the MyTime user interface changed to greek.

Are you saying that everything is in english or just some things are in english.  If you would like to help translate the english into greek I would appreciate the help.  I rely on volunteers to translate MyTime into different languages, the instructions are at http://priddysoftware.com/home/support/translation-instructions-2 if you are wanting to help.
