### ISSUE TITLE
Better Syncing Schedule?

### ISSUE THREAD

**Issue by appchasers** [toopriddy/mytime#285]
Hey Brother Priddy,

Still loving MyTime after all these years! But I can't help but wonder if there is a better time to prompt for syncing than when users launch the app. This does have its advantages because users have to process that screen before they can move on into the app. But the problem is that after sending the email, THEN users enter new data that will not have been in that backup. I've had to reset my iPhone a number of times in the past month. And never seem to get the most up to date info in my back up. But I don't want to identify a problem without proposing a solution. I know you can't know when someone is going to exit the app, so you cannot generate a backup dialogue before they quit. But how about:

1) a push notification 2 minutes after the user exits the app. After relaunching MyTime the backup dialogue will appear.
2) a user scheduled push notification to remind to backup.
3) a big backup button on screen at all times that send the email in the background. No dialogue box. Just confirmation.
4) if nothing else, build a url scheme into MyTime so that users can utilize apps like Launch Center Pro to schedule when to launch the app on a schedule.

Thanks for your consideration and hard work!

**Comment by toopriddy** [comment]
Thanks for the information.  I am currently testing a solution that will do
automatic backups to iCloud Drive.  This will allow the user to keep up
with a series of backups that will not be deleted when the user deletes the
app (which is the number one support email burden I have lately).  This
will never have to ask the user for input and will silently do work in the
background.  I make a backup before applying another backup ontop of MyTime.

You do bring up a good point about backing up AFTER entering in data.
Thanks for the input.

**Comment by appchasers** [comment]
Hi. Thank you for the reply! Actually, iCloud backup would be the best option! So I'm all for that.  Thanks for your hard work!!

**Comment by toopriddy** [comment]
The update has been out, if you are interested in commenting further on this feature please email directly toopriddy@gmail.com
