### ISSUE TITLE
Upload option - CSV?

### ISSUE THREAD

**Issue by kishonbiz** [toopriddy/mytime#286]
Is it possible to load RV's via CSV file or refresh via CSV? Thanks! -Kishon Monteith, Iowa City IA - English

**Comment by toopriddy** [comment]
I am looking into something like this for importing android ministry
assistant files into mytime.  Once I get one converter I can create another
one with less effort (though it will take time).

email me your example csv file (toopriddy@gmail.com) and I can see what you
are requiring.  Please reference this email github issue request in your
email as I get tons of email daily and I can never remember who is talking
about what if the emails are separated.
