### ISSUE TITLE
Placements not counted correctly

### ISSUE THREAD

**Issue by tevorb5417** [toopriddy/mytime#287]
After reviewing the latest change reflecting the new placements category, etc., I noticed that the placements totals in statistics was adding only the manually entered amounts and did not add placements entered in new calls or RVs.

**Comment by toopriddy** [comment]
Thank you for reporting this, I have reproduced this and will have it in the next update.  Hopefully this will be out before the january reports need to happen.

**Comment by toopriddy** [comment]
I have fixed this in the development version of MyTime, I should have an update to send to apple tonight or tomorrow night... busy week CA BR on saturday.

**Comment by toopriddy** [comment]
Apple Just approved the app, this should be fixed.
