### ISSUE TITLE
Pin Won't Drop

### ISSUE THREAD

**Issue by idezotl** [toopriddy/mytime#289]
Both with an auto lookup address and manually entered address the new Pins aren't adding. Happened on both my phone, also iPad. And on my wife's phone. iOS 9.2. iPhone 6+ and iPhone 6. And iPad Air. On my iPad Air I deleted my time then restored from backup. Also tried a fresh install and couldn't get it to map either. 

I was able to manually add the pin and location. 

Thank you for your hard work. Just wanted to let you know.

**Comment by toopriddy** [comment]
I have been able to reproduce this.  This sadly did not happen in beta versions of MyTime and is now only happening in the released version.  I will have to investigate what is going on.

**Comment by toopriddy** [comment]
This is fixed in the development version of MyTime.  A release will be sent to apple tonight or tomorrow night

**Comment by idezotl** [comment]
Thank you kindly. Thanks for all your hard work.

**Comment by toopriddy** [comment]
FYI: when you upgrade to the newest version of MyTime (whenever apple approves it) it will then start to lookup the GPS location of the addresses automatically.

**Comment by idezotl** [comment]
Thank you.

**Comment by toopriddy** [comment]
Apple Just approved the app, this should be fixed.
