### ISSUE TITLE
No backup mail possible to send

### ISSUE THREAD

**Issue by Kaijam** [toopriddy/mytime#291]
Cannot send backup mail.

**Comment by toopriddy** [comment]
Hello, Kaijam, I am sorry I don't have enough information to understand your problem.

You have to have settings enough for the "Mail" application on your iPhone to send email for any application to send email from a device.  

MyTime actually does not mail anything, it asks the "Mail" application to send an email in behalf of MyTime.  Any mail problem with MyTime could be:
1. mail settings in Settings App->Mail Contacts & Calendars-> is not setup appropriately
2. the default account in Settings App->Mail Contacts & Calendars-> is not setup appropriately
3. the outgoing email is stuck in the "outbox" for your email account, go to the Mail application, then hit the back button to see all of the mailboxes to see if you have something stuck in the outbox.

100% of problems associated with emailing from MyTime have been settings issues related to the Mail app settings.

**Comment by Kaijam** [comment]
Hi!

Thank you for your answer! 

Usually I have no problem with emailing from the app, only after the latest changes that were made because of the new way to report...

But I'll try your suggestions!
Thank you for help and thank you for a very nice app! :)

Greetings from the north of Sweden, Kaija Marklund

**Comment by toopriddy** [comment]
If you still have issues we can FaceTime call and try to work through the problem. Please provide me some opportune times to call, what timezone you are referencing and email me your appleid I can call 

Please email toopriddy@gmail.com instead of responding to this github email
