### ISSUE TITLE
My time backup not working on different device. 

### ISSUE THREAD

**Issue by kipara37** [toopriddy/mytime#292]
I use my iPhone to backup my service report every day, but would like to backup also to my iPad. However when I try to do this through my email, nothing happens. I have tried deleting the app on my iPad and reinstalling it, but it still won't allow me to backup. Can you tell me if there is a way I can do this? Thanks!

**Comment by toopriddy** [comment]
Sorry for the trouble, Please take a look to see if you are following the instructions from the FAQ http://priddysoftware.com/home/faq 

Things to note (if you are not receiving the backup email, I can't tell from your message):
1. MyTime does not actually email anything, this is taken care of by the "Mail" app on the device.
2. make sure the email sheet pops up for you to send the MyTime backup from your iPhone for you to press the "Send" button.
3. if you get and press the "Send" button, check to see if your email has not been sent by going to the "Mail" application and then tapping on the back button to go to all off your mailboxes to see if the email is stuck in the "Outbox"

If you are receiving the email backup, tap on the attached file, tap on "copy to MyTime" and then tap on restore.  
Make sure that the MyTime version you are running on both devices is the same version.
If your email backup does not have an attached file, it is possible that you have been emailing a printable email backup, which is not the "MyTime Email Backup"

I hope this helps, if not please email me directly at toopriddy@gmail.com

100% of problems (in the last 5 years) with email backup not working is associated with Mail settings, mail being stuck in the outbox or the wrong email backup being sent.

**Comment by toopriddy** [comment]
any update?

**Comment by kipara37** [comment]
I deleted and reinstalled it and it now seems to work. Thanks!
