### ISSUE TITLE
Bug in pioneer time calculations.

### ISSUE THREAD

**Issue by rwhite191** [toopriddy/mytime#294]
The time goal for months prior to the pioneer start date displays as though thecdate were earlier. Also, there is no provision for auxiliary pioneering for 30 hours and if you enter a custom goal it does the same for earlier months.

**Comment by toopriddy** [comment]
Hello rwhite191, Thank you for reporting an issue.  I do not have enough information to reproduce what you are experiencing regarding the pioneer start date.

If I set the pioneer start date and set the goal type to "by type" pioneer goals do not start till the pioneer start date.  If you set a custom goal it overrides any setting you have for pioneer start date

Currently there is no support for a single month custom goal, this is on the feature request list on the MyTime website http://priddysoftware.com/home/support/feature-request-list

**Comment by toopriddy** [comment]
closing due to lack of response
