### ISSUE TITLE
App crashes when taking a photo

### ISSUE THREAD

**Issue by baerwurzl** [toopriddy/mytime#297]
Hy

I just downloaded the new version of mytime and wanted to add pictures. But always when clicking on "set picture" the screen gets black with "takephotobutton" and crashes. Forcequit doesnt help. Crashes in territorries and visits.

Bye Ben

**Comment by baerwurzl** [comment]
iPad Mini 4 newest iOS

**Comment by idezotl** [comment]
iPad Pro 9.7" iOS 9.3.2 
Mytime crashes when I tap on 'set picture' tried a force quit of the app, also a restart of the iPad. Will backup and try a reinstall of Mytime.

**Comment by toopriddy** [comment]
Hello everyone, I am sorry for the trouble.  This is an issue on the iPad only.  I have fixed this in the development version and am submitting to apple right now.
