### ISSUE TITLE
Blue Location Dot on Mapped Calls Screen

### ISSUE THREAD

**Issue by lainie45** [toopriddy/mytime#304]
After I OS 10 software with downloaded, the blue location dot on the Mapped calls screen  is no longer visible.

**Comment by toopriddy** [comment]
Hello, this is due to location services being turned off in the settings app->privacy->location services. Please turn it on and scroll down to MyTime and make sure it is turned on there too. 

MyTime can not turn this off, the only way this gets turned off is manually.
