### ISSUE TITLE
Can’t restore

### ISSUE THREAD

**Issue by SimonFSmith** [toopriddy/mytime#320]
I saved my datas on my iCloud account and when I wanna have them back, the app tells me that it didn’t work and that I should look if I’m connected to internet, wich I am (tried on my ipad and iphone too).

**Comment by toopriddy** [comment]
Sorry for the trouble, This is an iOS 11 bug that I am looking into. I know what is happening based on a incompatible change apple did in iOS 11. I will be looking at a fix tonight.

**Comment by ghost** [comment]
Thank you so much!

Simon
