### ISSUE TITLE
Pioneer hour count incorrection 

### ISSUE THREAD

**Issue by ameliabell** [toopriddy/mytime#329]
My profile is set under regular pioneer so my monthly goal is 70 hours but each month the total is less than 70 even if I haven’t carried time over. The yearly count is correct just each month my goal is incorrect. 

Thanks

**Comment by toopriddy** [comment]
Hello , sorry for the confusion. MyTime calculates your monthly goal based on the average monthly hours to reach your pioneer year goal. So for instance if you get more than 70 hours in the previous months then your average monthly goal to reach your yearly goal will be lower than 70 hours. Conversly if you do not make 70 hours in previous months then you will have to do more than 70 hours in future months to make up the difference. MyTime calculates based on meeting the year target not a fixed 70 hours monthly target. You can change it to do a strict 70 hours but it is interferes with pioneer credits and most pioneers seem to like the calculated goal once it is explained that it is not a calculation error. I hope this helps.

**Comment by ameliabell** [comment]
Brilliant, thanks for your help!
