### ISSUE TITLE
Losing RV entries

### ISSUE THREAD

**Issue by freedlun** [toopriddy/mytime#343]
Just last night I entered an RV for a student.
This morning it wasn’t there. I thought perhaps I forgot to save, so I entered it again.
Then I noticed last weeks I go was home too! This is a scary bug.
Fortunately I just happen to back up yesterday. Please look into it.

Thanks!

**Comment by freedlun** [comment]
Update: It seems this call has 2 entries. But only one pin is showing. Even on full zoom. Fixed it by manually moving the pin. Whew! That had me worried. Sorry for the alarm. 

I don’t know. What I’d do without this app.👍🏽

**Comment by toopriddy** [comment]
I am sorry for the delay in response, (regional season fills up my inbox
and time)

If you tap on the pin for the call to bring up the information bubble and
then tap the pin again it will rotate through the calls at the same
location.  There is a feature request at
http://priddysoftware.com/home/support/feature-request-list which asks for
making this more apparent.

I hope this helps

**Comment by freedlun** [comment]
Thanks so much! I have figured that out. In fact that is what led me to have split my RV records between two records.  

Scott

**Comment by toopriddy** [comment]
closing issue
