### ISSUE TITLE
Statistics incorrect with multiple credit hour categorys (Bethel Remote & LDC)

### ISSUE THREAD

**Issue by johnapineda2** [toopriddy/mytime#345]
I am a Remote Bethelite and was just asked to help with a LDC VSG effort as well.  Ive reached my 65 hour goal for the month just with my 32 regular hours and 35 LDC hours.  My 25 Bethel hours are being added to my Statistics total incorrectly.  Thank you.

**Comment by toopriddy** [comment]
Hello, sorry for the trouble.  Could you please email me directly with your
email backup by going to MyTime->More->Settings->Email Backup->Email MyTime
Backup to toopriddy@gmail.com and letting me know too what the expectation
you were seeing about the Bethel hours was incorrect.  This way I can
understand better what is going on?

Please do not directly reply to this email as it will be posted publicly,
please send your email backup and details to my email toopriddy@gmail.com

**Comment by toopriddy** [comment]
closing, either this has been resolved over email or no reply.
