### ISSUE TITLE
In ‘city sorted’ view, cities are duplicated in the blue column on the right, and the rvs are sorted randomly between duplicate city groups. I’d be happy to attach a screenshot, but cannot figure out how to do that.

### ISSUE THREAD

**Issue by twrnkls** [toopriddy/mytime#350]

**Comment by toopriddy** [comment]
I am sorry for the trouble, MyTime treats the city field as you entered the text.  Try this: go to one of the calls in the duplicated cities, in fact try one from the second section of cities (separated by the sections) and tap on the call, tap edit and then tap on the address, you might notice that you have a space at the end of the city.  If you delete the space at the end on this and the other calls that accidentally have whitespace at the end of the city names you will remove your duplicate cities.

I hope this helps
