### ISSUE TITLE
New iPhone 8; data won't restore

### ISSUE THREAD

**Issue by Hwynette** [toopriddy/mytime#351]
Hello.  Just got my iPhone 8.  Reinstalled MyTime 3.9.10(1) on the 8.  Opened my last email backup (sent earlier today) and nothing happens.

The screen shows backup.mytimedb
MyTime Database

My only options are "done" and "share"

Advice?  Thank you

**Comment by Hwynette** [comment]
Oh, duh, didn't realize I had to select the 'share' button.  Disregard and sorry/thanks!

**Comment by toopriddy** [comment]
I am glad you have it worked out. When you get a new device when setting it up you can hold it beside the old iPhone and transfer all data and settings (like MyTime data) where you do not have to setup anything new. If you have not spent a lot of time on this and you have your old device you can go to the settings app -> general->reset and erase all content and settings to re-setup the device using the old device. This way you keep pictures and settings and all

**Comment by Hwynette** [comment]
👍👍👍
