### ISSUE TITLE
Unable to send report 

### ISSUE THREAD

**Issue by hereiambluejae** [toopriddy/mytime#352]
iPhone Xr running iOS 12.1
New phone, forgot to back up hours, etc, oh well. Input information for desired month to send selected “pick months to send” selected month and “send” button never lit up.

**Comment by toopriddy** [comment]
Hello, sorry for the trouble. MyTime automatically backs up to iCloud for you if you have not disabled iCloud for MyTime. Go to MyTime->More->Settings-> Backup-> tap on iCloud and then scroll down and tap on the top most backup from before changing phones and then follow the onscreen prompts to completely change/replace your current data to what you had before. 

If your send button is grayed out then the to address at the top of that window has not been properly filled out, by default it is using email and if you want to use SMS you can go to MyTime->More->Settings-> send report using X-> and change this to what you want. 

MyTime sends email using the apple Mail application so your mail account needs to be setup before it can be used. 

If you have your old device you could completely transfer all of your phone data and settings from the old phone by deleting all of your phone data by going to the settings app-> general-> reset all content and settings. And then when it is starting up new asking you to pick the language and stuff put the new phone close to the old phone (can’t remember what it minimum has to be) and select the quick restore. Instructions from apple are here https://support.apple.com/en-us/HT201269

**Comment by hereiambluejae** [comment]
Shoot, now I feel really dumb. I just hadn’t input an email for the secretary. Sorry to waste your time. That was the main thing. I had already restored the old phone when I realized about the data, and I must have turned off auto backup sometimes earlier this year. Live and learn I guess. Thanks for your time.
