### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by debbifrago** [toopriddy/mytime#353]
Hi! I have an IPhone 7 Plus and I’m using 3.10.0 (1) version of MyTime.
today I tried to backup by email. The app creates the mail with the file and inserts my destination email automatically but does not allow me to send it. the word "send" does not turn blue but remains gray. thank you so much.

**Comment by toopriddy** [comment]
Hello Debbi, at the point of the email being shown it is actually the apple Mail application which is sending the email and not MyTime. Please make sure that you have the apple Mail application setup with an email account (not a third party email application line the gmail app or outlook). If you can send an email to yourself from the apple Mail application then I would suggest checking the destination email address that is inserted to see if there is an issue. I hope this helps

**Comment by debbifrago** [comment]
Yes, I used Gmail. Now I solved it!! Thank you so much!
