### ISSUE TITLE
Remote worker time is incorrect 3.10.1 (1)

### ISSUE THREAD

**Issue by BoxOfSnoo** [toopriddy/mytime#355]
The update notes said this was fixed, but it’s incorrect now.  Previous months say goal of 65 met (should be 70), and this month says 13 hours for Bethel and 50h 20m for goal - strange math...

**Comment by BoxOfSnoo** [comment]
Ok I see my confusion with goal vs hour cap (which is not displayed).  There is still the strange math to handle...

**Comment by toopriddy** [comment]
Hello, sorry for the confusion. MyTime does an average monthly hours calculation to reach the yearly goal. So if you have less than 65 hours in previous months then ToR monthly average to reach the year goal will be more than 65 for the month. Conversely if you got more than 65 per month the monthly average needed to reach the yearly goal would be less than 65. 

There is more info about this on the FAQ http://priddysoftware.com/home/faq

**Comment by BoxOfSnoo** [comment]
Shouldn’t this say “average” somewhere in there to make it clear?

**Comment by toopriddy** [comment]
I will take it into consideration, sadly the screen is already super busy
with text.  I will most likely turn it into a popup hint
