### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by janeill** [toopriddy/mytime#359]
My map is not showing any of my return visits. Is anyone else having this problem?

**Comment by toopriddy** [comment]
Hello, currently I am not able to reproduce your findings. Please check the MyTime FAQ on the reasons why this would be happening. Http://priddysoftware.com/home/faq under mapped calls. 

The main reason this would happen is if the address information is not separated into the individual fields (house number should be separate from street name) and the city and state have to be all filled out. 

I hope this helps, if not please send me your email backup by going to MyTime->More->Settings->Email Backup->Email MyTime Backup to toopriddy@gmail.com and tell me which calls I should look at

**Comment by janeill** [comment]
Hi! Thanks for the info. I saw I was missing the state for each of my calls and I went through and manually inserted and now all calls show up on my map. 

Thanks!
