### ISSUE TITLE
Time Incorrectly Reporting

### ISSUE THREAD

**Issue by Drakes86** [toopriddy/mytime#361]
When entering service time for a month, if the time in the ministry exceeds 70 hours for a pioneer, but then additional service hours like LDC time, is counted directly to the total credits instead of capping at 70. 

i.e. May report 80 ministry hours, LDC report 20 hours
for summary, it is counting the 20 LDC hours as credit, instead of counting 0 credit hours.

**Comment by toopriddy** [comment]
Please check under Hours Tab->tap on the top hours-> tap edit-> tap "LDC"-> make sure you have not turned on "direct credits" for LDC.  If this is turned on then it was manually enabled to make LDC be a direct credit. LDC credit hours are not direct credits, only pioneer school or language school hours are direct credits.

I hope this helps
