### ISSUE TITLE
New Service Year Reset

### ISSUE THREAD

**Issue by sybilmarie** [toopriddy/mytime#367]
I’m a reg pioneer and when the new service year began it showed that I already had 15 hours. While that’s great and all (*wink*) I’m trying to set the goal at 840 hours. I went back in the different ways to log your time and I don’t have anything logged for 2019-2020 service year.

**Comment by toopriddy** [comment]
Hello, sorry for the trouble.  This was fixed Monday and a build provided
to apple to update everyone.  Sadly I am still waiting on it being reviewed
before people will see the fix.
Thank you for reporting it.  This had to do with if you added a "Field
Service" hours category to classify different types of field service that
the service year was calculated wrong for them.

**Comment by sybilmarie** [comment]
Thank you very much for your hard work brother and I look forward to the fix. I had a hunch that’s what it could be. Keep up the great work!! 👍🏻
