### ISSUE TITLE
Restore BackUp from email not working

### ISSUE THREAD

**Issue by AuntiMonti** [toopriddy/mytime#370]
Thank you for all your hard work on this program!  

I love MyTime.  I’ve been using it for years and recommend it to friends and encourage them to donate if they like it.  

I’m trying to keep a duplicate of my data on my iPad although I don’t do it as often as I should.  I’ve always used email backup & restore feature to sync to my ipad from my iphone (which is the more current data).  For some reason I’m unable to update from the email.  It doesn’t open MyTime automatically like it used to.  It just sits. 

I’m using IOS 12.4.1 on a 1GB WiFi connection.  I’m attempting to attach a screenshot.

![43FD6FCA-F1E6-49FC-A445-5C0F318CBF24](https://user-images.githubusercontent.com/51581286/65389680-970c7480-dd0d-11e9-8ce7-f38d5a472eee.png)

**Comment by toopriddy** [comment]
please tap on the box with the arrow jumping out if it at the top right and select "copy to MyTime" and then it will restore.  This is a workflow issue in the Mail application where it attempts to "read" the attached file instead of asking you to open it in another file.

sorry for the trouble

**Comment by AuntiMonti** [comment]
Thank you Brother. That worked perfectly!

From Monti's iPhone

> On Sep 30, 2019, at 6:49 AM, toopriddy <notifications@github.com> wrote:
> 

﻿
Closed #370.
