### ISSUE TITLE
Time miscalculation

### ISSUE THREAD

**Issue by MaxCash** [toopriddy/mytime#376]
October has my time recorded at 55 hours and 10 minutes.  However the stats show 11 hours and 6 minutes needed for the goal.  It doesn’t make sense.  Noticed September was odd a well- shoes an annual goal ending Xxx and 21 minutes however all my time was rounded in 5 minute increments.  Thank you

**Comment by toopriddy** [comment]
Hello, sorry for the confusion. MyTime calculates the monthly average to meet the yearly goal. If you do more than 70 hours in previous months then tor monthly average to meet your yearly goal will be less than 70 hours per month. If you made less than 70 hours in previous months then the monthly average hours to meet the yearly goal will be more than 70 hours per month. 

I hope this helps. If you feel there is still a problem please email your MyTime backup by going to MyTime->More->Settings->Email Backup->Email MyTime Backup to toopriddy@gmail.com and I can see what is going on

I hope this helps
