### ISSUE TITLE
Calculations for time are off

### ISSUE THREAD

**Issue by jessica101872** [toopriddy/mytime#378]
For some reason the total amount in red is off. The amount total for the year remains correct. 

![C3A93F04-2880-4FC8-807C-A88A807B6910](https://user-images.githubusercontent.com/57140003/67768935-f145d700-fa29-11e9-8176-481c94ec265a.png)
![3608337C-FC4B-4D0D-ACC5-F501FB143D29](https://user-images.githubusercontent.com/57140003/67768936-f145d700-fa29-11e9-903b-b83214393434.png)

**Comment by toopriddy** [comment]
I am sorry for the confusion.  MyTime calculates the monthly average to achieve your yearly goal.  There is a lengthy explanation at the top of the FAQ which might help to understand what it is trying to do for you.  http://priddysoftware.com/home/faq

I hope this helps

**Comment by jessica101872** [comment]
Thanks! The explanation makes sense. It looks like if I set a custom goal
of 70 hours, then it remains the expected count down and still keeps the
annual count down going.

Thanks!!
