### ISSUE TITLE
Bug in the Monthly hours 

### ISSUE THREAD

**Issue by screamingdasies** [toopriddy/mytime#379]
Hello, 

There has been a couple people that have had a problem with  their hourly report saying that they need to still get extra minutes to fulfill their time requirements for the month as a pioneer. (Underneath where it says Hours on the “Statistics” tab.) The hours in the “Hours” tab have no minutes added to them except for in 30 minute increments. 

We tried rounding up the time for one month from 69 hours and 30 minutes to 70 hours but it says underneath, “Achieved goal of 69 hours 49 minutes”. 

Please let us know if there is anything we can do on our end. 

Thanks so much!  This app is a lifesaver! Such a blessing from Jehovah! Keep up the good work! 
![F1F7C998-AC2B-4E9A-992A-6599B9B528B1](https://user-images.githubusercontent.com/57230612/67968863-17a87580-fbd6-11e9-8280-21f27617b586.png)
![50099852-80D7-4A3F-8007-6938C4B71674](https://user-images.githubusercontent.com/57230612/67968883-2000b080-fbd6-11e9-9505-8f19df581306.png)

Agape’,
Katie Alexander

**Comment by toopriddy** [comment]
Hey Katie, sorry for the confusion.  If you are a pioneer (and have set MyTime->More->Settings->Publisher Type-> to pioneer). Then it will calculate your monthly goal based on your average hours per month to accomplish your yearly goal.  70 hours a month is an average if you meet 70 hours per month, but if you achieved more than 70 hours in previous months then future months only have to have less than 70 hours per month on average to achieve the yearly goal, conversely if you were only able to meet 60 hours in previous months then the average hours needed per month to meet the yearly goal would be more than 70.
If you have LDC credits:MyTime calculates the LDC credits based on the branch recommendations which have recently changed from being able to increase your hours that count towards the yearly goal from 70 hours to 75 hours per month.  So for instance if you got 60 hours in a month and then did 50 hours LDC, only 15 hours of those LDC hours count as credits, the rest do not carry over to the next month.
These LDC hours are taken into account with the monthly goal as well as the service year (you can see in the service year how many LDC hours contribute as credits based on the note below them).  So your monthly goal just will reflect how many more hours to achieve a monthly average which will get you to the goal you signed up for which was the yearly 840 goal (if you started in the middle of the service year, mytime will take that into account as well).
I hope this helps.
