### ISSUE TITLE
Search in MyTime: only in names

### ISSUE THREAD

**Issue by eflix443** [toopriddy/mytime#380]
In the search of interested ones by name I can no longer change the category to address, notes or all.

**Comment by toopriddy** [comment]
Thank you for reporting this, it is currently a duplicate issue reported already at https://github.com/toopriddy/mytime/issues/377

Sadly Apple broke a lot of software in iOS 13 when they completely rewrote the navigation bar and search bar code.  Sadly this is a bug in iOS 13 and we are waiting on a fix from apple.  As a workaround you can rotate your phone sideways and press the buttons but when in portrait the buttons are not available to press.
